### ISSUE TITLE
程序是跑在哪里啊

### ISSUE THREAD

**Issue by longxiaonan** [beatfan/ScanGun#1]
您好，可以介绍下组网的架构吗，我想学习下，然后看是跑在哪里的啊

**Comment by beatfan** [comment]
> 您好，可以介绍下组网的架构吗，我想学习下，然后看是跑在哪里的啊

不好意思，Github没有提醒我有这个issue，一直没注意。
这个是跑在摩托罗拉扫码枪上的，WinCE6.0系统，组网核心处理还是在服务器上，扫码枪仅仅是跟服务器通信，上传和下载信息。
